Desc timestamp 1.3
basho/riak_test pull request #1055
Opened 2016-04-22 11:22 UTC by andytill

Tests for descending keys.

2016-07-20 18:51 UTC, javajolt commented on tests/ts_updown_select_SUITE.erl
> +-module(ts_updown_select_SUITE).
Since this is a cluster, I would suggest `ts_cluster_updown_select_SUITE`

2016-11-03 13:26 UTC, gordonguthrie commented
+1 6681d5d

2016-11-04 15:56 UTC, javajolt commented
@andytill Why do we have so many changes on this?  Was this some very old version which you started from? Maybe we could rebase your changes?

2016-11-15 00:53 UTC, hazen requested changes
Let me know your thoughts on my comments. Thanks!

2016-11-15 00:53 UTC, javajolt commented on run_tests.sh
> +./riak_test -c rt_ts -t tests/ts_updown_select_SUITE.erl
This seems pretty specific.  Was this meant to be included in this PR?

2016-11-15 00:53 UTC, javajolt commented on src/riak_test_escript.erl
> +                %% TODO don't understand what this does
Did you want to add this comment?  I can explain (more) of what this is meant to do.  When `riak_test` was written it was supposed to run a whole bunch of tests sequentially and this shuffles the order.  Not that useful now that we have independent tests on giddyup.  It was meant to break any potential test interdependence.

2016-11-15 00:53 UTC, javajolt commented on tests/ts_cluster_ddl_upgrades_SUITE.erl
> +    % ct:pal("VERSION 1.4 ~p", [rt:find_version_by_name(["riak_ts-1.4.0", "riak_ts_ee-1.4.0"])]),
Mean to leave this in?

2016-11-15 00:53 UTC, javajolt commented on tests/ts_updown_select_SUITE.erl
> +-module(ts_updown_select_SUITE).
Yup. Still think that's a more consistent name

2016-11-15 09:35 UTC, andytill commented on src/riak_test_escript.erl
> +                %% TODO don't understand what this does
Not sure where that is from. I need to rebase this, it will probably disappear then.

2016-11-15 16:36 UTC, gordonguthrie commented on src/riak_test_escript.erl
> +                %% TODO don't understand what this does
I left it in there - it was something to do with parallel tests running in the cloud - but I don't understand why/how it is used...

2016-11-16 19:05 UTC, javajolt commented
Think we'll need a rebase on this PR since I doubt we actually have 103 relevant file changes...

2016-11-16 21:02 UTC, andytill commented
I will close this one and open another PR tomorrow, something went very wrong with the rebase I did today.

2016-11-17 16:05 UTC, andytill commented
Closing and reopening as https://github.com/basho/riak_test/pull/1200

2016-11-17 16:05 UTC, closed without merging