Merge develop-2.2 into riak_ts-develop
basho/riak_test pull request #1168
Opened 2016-10-18 20:54 UTC by korry8911

So I made a branch off of riak_ts-develop, merged in develop-2.2 which required resolving 3 conflicts. @javajolt

2016-10-18 21:56 UTC, hazen requested changes
Once the conflicts are resolved, we should be good to go

2016-10-18 21:56 UTC, javajolt commented on rebar.config
> +<<<<<<< HEAD
@korry8911 We have merge-conflict here.  You'll want the deps in the `HEAD` section except for the addition of the `rebar_lock_deps_plugin` we just added.  That needs to come from the `develop-2.2` side.

2016-10-18 21:56 UTC, javajolt commented on src/riak_test_escript.erl
> +<<<<<<< HEAD
Another conflict.  Here we want to take the `develop-2.2` side instead.

2016-10-18 21:56 UTC, javajolt commented on src/riak_test_escript.erl
> +<<<<<<< HEAD
Conflict. Here we actually want to keep both sides.

2016-10-18 22:12 UTC, korry8911 commented
ok, I think the conflicts have been resolved correctly now. @javajolt

2016-10-18 22:21 UTC, hazen requested changes
Once these change have been made:
- build your branch
- run a simple test, like basic-command-line to see that it works

Remember this is against: Riak TS

2016-10-18 22:21 UTC, javajolt commented on src/riak_test_escript.erl
>                      [ giddyup:post_artifact(Base, File) || File <- rt:get_node_logs() ],
Lines 328-333 need to be removed.  This was an either/or decision and we are choosing *only* the `develop-2.2` changes

2016-10-18 22:21 UTC, javajolt commented on rebar.config
> +
We can kill this blank line

2016-10-18 22:59 UTC, korry8911 commented
ok, build riak_test and ran basic_command_line:
Test Results:
basic_command_line-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
---------------------------------------------
0 Tests Failed
1 Tests Passed
That's 100.0% for those keeping score
@javajolt

2016-10-19 01:18 UTC, hazen approved these changes

2016-10-19 01:18 UTC, javajolt commented
:+1:

2016-10-19 01:18 UTC, merged