Pass in tests to riak_test script as comma separated values
basho/riak_test pull request #1186
Opened 2016-11-04 21:32 UTC by korry8911

Added some code to riak_test_escript to allow passing in of comma separated test values after the -t flag. Example usage would be:
```
 ./riak_test -c rtdev -t test_a,test_b,test_c
```

If you pass in repeated tests, the test is only run once. The following examples will run test_a once:
```
 ./riak_test -c rtdev -t test_a,test_a,test_a
 ./riak_test -c rtdev -t test_a,test_b,test_a
 ./riak_test -c rtdev -t test_b,test_a,test_a
```

tests must be comma separated with no whitespace in between.
@javajolt

2016-11-04 21:38 UTC, andytill commented
@korry8911 great that this is being looked at! Requiring that these are comma separated means that it is not possible to use bash file wild cards. For example, if I want to run all the tests for Riak Time Series I would want to run `-t tests/ts_*` and have the tests be all of the arguments after `-t`.

2016-11-04 22:07 UTC, javajolt commented
@korry8911 So Andy brings up a good point.  It would be nice to support wildcards, too.  Beyond that, it would be nice to have the parser allow spaces between the test names as a convenience, e.g.
`-t ts_simple_select, ts_cluster_comprehensive`

2016-11-04 22:07 UTC, korry8911 commented
@andytill so it seems that with wildcards, ts_* would be expanded into a whitespace separated list.  The library used in riak_test_escript is getopt and has a restriction on white spaces: https://github.com/jcomellas/getopt#arguments-with-embedded-whitespace. To use white spaces, the argument must be enclosed by \", like \"test_a test_b test_c\". I'm pretty sure using bash wildcards does not work within quotes. But, there is probably a way to expand the wildcards from within erlang.  Let me know if you have any ideas or suggestions.

2016-11-04 22:47 UTC, korry8911 commented
@javajolt @andytill so a temp work around could be to use:
```
./riak_test -c rtdev -t $(echo tests/ts_* | sed 's/ /,/g')
```

2016-11-04 22:54 UTC, andytill commented
getopt supports non-option args at the end  of the command line which could be used for test suites, however this is already being used for `HarnessArgs`.

https://github.com/basho/riak_test/blob/be0f135b7d56d93bf486e85bc46ac2f994f0975f/src/riak_test_escript.erl#L68

I don't think this is actually used anywhere so could be re-purposed, but you'd have to double check.

This bash snippet can be used to run multiple tests currently in rt.

```shell
./riak_test -c rtdev `sh -c 'for i in tests/ts_*; do echo -t $i; done'`
```

2016-11-07 15:36 UTC, korry8911 commented
@andytill @javajolt i think the problem with using HarnessArgs would be that the tests being passed in will be split among two different variables:

```
./riak_test -c rtdev -t testA testB testC
```

testA will be in the ParsedArgs and then testB and testC will be in harness args.... I don't see a clean way to reconcile the two, but there is a way. If this is the prefered option i can modify the code to assume arguments in harness args should be added to the test args. In fact, we could just drop the -t flag all together and make harness args the default way to pass in tests. Thought?

2016-11-07 17:02 UTC, andytill commented
I like it, I am in favour of repurposing `HarnessArgs` as long as we don't break anything. Maybe keep the `-t` option around for a while until people get used to a life without it :)

2016-11-07 18:23 UTC, korry8911 commented
@andytill @javajolt ok so i reworked this to support passing in comma separated lists which can contain wildcards. There two caveats. 1) if you pass in a single wildcard, you must enclose in quotes, this is due to shell completing the expression, and 2) if you pass in wildcards, you must pass in the test with its directory. The following are examples running from /riak_test:

```
BAD USAGE
./riak_test -c rtdev -t ts_simple_* %% no tests run
./riak_test -c rtdev -t "ts_simple_* %% no tests run
./riak_test -c rtdev -t ts_simple_*,yz_handoff %% only yz_handoff run

GOOD USAGE
./riak_test -c rtdev -t "tests/ts_simple_*" %% will run all matching tests from ./tests directory
./riak_test -c rtdev -t tests/ts_simple_*,yz_handoff %% will run all matching tests in ./test and yz_handoff
./riak_test -c rtdev -t "tests/ts_simple_*","tests/ts_cluster_*",yz_handoff 
./riak_test -c rtdev -t tests/ts_simple_*,"tests/ts_cluster_*",yz_handoff 
./riak_test -c rtdev -t tests/ts_simple_*,tests/ts_cluster_*,yz_handoff
```

2016-11-07 22:00 UTC, korry8911 commented
@andytill @javajolt ok, so I made it much better. You can now pass in really anything. No quotes needed for anything. The script will now search for tests using wildcards in the directories specified in riak_config for test_paths. If it cant find the tests in there is makes one last try in the `./tests/` directory in riak_test. If you supply a prefix it will just use that. So now here are example usages:

```
GOOD USAGE
./riak_test -c rtdev -t ts_cluster_*
./riak_test -c rtdev -t tests/ts_cluster_*
./riak_test -c rtdev -t ts_cluster_*,ts_simple_*,yz_handoff
```

2016-11-07 22:02 UTC, javajolt commented
How exciting! I can't wait to try it out

2016-11-08 00:41 UTC, hazen requested changes
Code works great! However there are some optimizations we can add to make it a bit more efficient and compact.

2016-11-08 00:41 UTC, javajolt commented on src/riak_test_escript.erl
> +    WCTestsNoPrefix = [get_test_with_valid_prefix(TestA, RTTestPaths) || TestA <- CommaSepTests, get_test_type(TestA) =:= yes_wc_no_prefix],
Looks like by building 4 lists you are touching each test 4 times.  How about move through the list once, but for each element in the perform different logic.  Maybe first check to see if it has a wildcard.  If so, then expand the list of test names.  You could use `lists:foldl` to build an accumulator of additional tests.  Before adding all of those tests to the list, then you could compare each new one to see if it has a prefix and see if it needs to be added to the code path and stripped from the test name.

Happy to discuss to clarify what I'm suggesting.

2016-11-08 00:41 UTC, javajolt commented on src/riak_test_escript.erl
> +    RTTestPaths = rt_config:get(test_paths, ["tests"]),
How about we simply have a default value of `[]` and return the value of `rt_config:get/2` concatenated with `tests`?

`[rt_config:get(test_paths, [])|["tests"]]`

2016-11-08 00:41 UTC, javajolt commented on src/riak_test_escript.erl
> +get_test_with_valid_prefix(Test, TestPaths) ->
You could use `lists:foldl` instead of do-it-yourself recursion.

2016-11-08 00:41 UTC, javajolt commented on src/riak_test_escript.erl
> +    {CodePathList++CodePaths, TestNameList++TestNames}.
List concatenation is more efficient than the `++` operator, as in the original code

2016-11-08 00:41 UTC, javajolt commented on src/riak_test_escript.erl
> +    CodePathList = [filename:dirname(TestName) || TestName <- AllTests],
We can probably combine this so it only passes over the tests once.  Actually we might be able to build a list of tuples of code path and test and `lists:unzip/1` them when it's time to return the values.

2016-11-09 18:17 UTC, korry8911 commented
@javajolt ok I added some of the suggestions you made... the only exception I think is that I use ++ still in some locations because we are concatenating two lists and not just adding an element to the head of a list.

2016-11-09 22:27 UTC, korry8911 commented
@javajolt @andytill ok, so it should be good to go know, barring any more comments...

2016-11-09 22:46 UTC, hazen commented on src/riak_test_escript.erl
> -get_test_with_valid_prefix(Test, TestPaths) ->
I like it!

2016-11-09 22:46 UTC, hazen approved these changes

2016-11-09 23:26 UTC, javajolt commented
:+1:

2016-11-09 23:27 UTC, merged

2016-11-10 08:39 UTC, andytill commented
Nice 👍