Desc Keys Tests 2
basho/riak_test pull request #1200
Opened 2016-11-17 16:04 UTC by andytill

Tests for descending keys in Riak Time Series.

2016-11-17 16:05 UTC, javajolt commented
🎉  Looks much better this time around

2016-11-17 16:07 UTC, andytill commented
@javajolt copy/paste FTW!

2016-11-18 00:05 UTC, javajolt commented
Looks like `ts_cluster_keys_SUITE` and `ts_simple_single_key_ops` pass, but `ts_cluster_select_desc_SUITE` and `ts_cluster_stream_list_keys_SUITE` have test failures. I'll need to crack the HTML of common test to find out why.

2016-11-18 00:13 UTC, hazen requested changes
Once these have been migrated away from `ts_util`, they might pass

2016-11-18 00:13 UTC, javajolt commented on tests/ts_cluster_select_desc_SUITE.erl
> +    [_Node|_] = Cluster = ts_util:build_cluster(multiple),
Looks like it should be `ts_setup:build_cluster(3)`

2016-11-18 00:13 UTC, javajolt commented on tests/ts_cluster_stream_list_keys_SUITE.erl
> +    [Node|_] = Cluster = ts_util:build_cluster(multiple),
Looks like it should be `ts_setup:build_cluster(3)`

2016-11-18 00:13 UTC, javajolt commented on tests/ts_cluster_stream_list_keys_SUITE.erl
> +    ts_util:create_and_activate_bucket_type(Cluster,
Needs to be broken into
```
    ts_setup:create_bucket_type(Cluster, DDL, Table),
    ts_setup:activate_bucket_type(Cluster, Table),
```

2016-11-18 00:13 UTC, javajolt commented on tests/ts_cluster_stream_list_keys_SUITE.erl
> +    ts_util:create_and_activate_bucket_type(Cluster,
Needs to be broken into
```
    ts_setup:create_bucket_type(Cluster, DDL, Table),
    ts_setup:activate_bucket_type(Cluster, Table),
```

2016-11-18 10:07 UTC, andytill commented on tests/ts_cluster_select_desc_SUITE.erl
> +    [_Node|_] = Cluster = ts_util:build_cluster(multiple),
Fixed in 619abbe

2016-11-18 10:07 UTC, andytill commented on tests/ts_cluster_stream_list_keys_SUITE.erl
> +    [Node|_] = Cluster = ts_util:build_cluster(multiple),
Fixed in 619abbe

2016-11-18 10:07 UTC, andytill commented on tests/ts_cluster_stream_list_keys_SUITE.erl
> +    ts_util:create_and_activate_bucket_type(Cluster,
Fixed in 619abbe

2016-11-18 10:07 UTC, andytill commented on tests/ts_cluster_stream_list_keys_SUITE.erl
> +    ts_util:create_and_activate_bucket_type(Cluster,
Fixed in 619abbe

2016-11-18 10:09 UTC, andytill commented
@javajolt  I had been compiling with an old `ts_util.beam` file in my ebin directory without realising it, so the tests were passing fine locally. Everything has been updated to use the new utils. Great review and comments, thanks!

2016-11-18 16:20 UTC, hazen approved these changes

2016-11-18 16:25 UTC, javajolt commented on tests/ts_cluster_select_desc_SUITE.erl
> +init_per_group(use_ttb_true, Config) ->
Love that you are testing both of these cases

2016-11-18 16:30 UTC, javajolt commented
:+1: 619abbe

2016-11-18 16:56 UTC, andytill commented on tests/ts_cluster_select_desc_SUITE.erl
> +init_per_group(use_ttb_true, Config) ->
@javajolt  Thanks, I meant to show you at Burlington but I was hustling DDL upgrades before my hols. We could trivially apply this to some other suites.

2016-11-18 16:56 UTC, merged