Added regression tests for sql delete
basho/riak_test pull request #1216
Opened 2016-11-30 09:14 UTC by gordonguthrie

2016-11-30 16:51 UTC, hmmr requested changes
A failing DELETE query would be good.

2016-11-30 16:51 UTC, hmmr commented on priv/riak_shell/riak_shell_regression1.log
> +{{command, "select * from GeoCheckin where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000;\n"}, {result, "Error (1001): Too many subqueries (7)"}}.
Does this error still encountered in the wild?

2016-11-30 16:51 UTC, hmmr commented on priv/riak_shell/riak_shell_regression1.log
> +{{command, "delete from deletetable where myfamily = 'berl' and myseries = 'saf' and time = 3;"}, {result, ""}}.
A DELETE query with incomplete values in WHERE clause would be appropriate.

2016-12-01 19:34 UTC, hmmr approved these changes

2016-12-01 19:34 UTC, hmmr commented
+1

2016-12-01 20:01 UTC, paegun commented on priv/riak_shell/riak_shell_regression1.log
> -555,1.1,10.0,0.01123
This line should not have been removed. There should be 3 rows returned. Perhaps it's a bit confusing b/c of the intentionally hardcoded values in the SELECT clause, but this is testing A) the number of rows returned; B) that values of each of the types in the SELECT clause are properly returned.

2016-12-01 20:33 UTC, paegun commented
+1 on the feature under test.

The issue requiring re-adding the line from regression log is due to the columns of a SELECT statement containing only literal values being reported as what looks like a row. When we have aliasing via `AS` this regression log line can be made more clear, making it less likely to confuse the next person.

2016-12-01 20:35 UTC, hmmr commented
+1

2016-12-01 20:35 UTC, merged