[WIP] new module ts_simple_percentile
basho/riak_test pull request #1270
Opened 2017-02-07 03:03 UTC by hmmr

RTS-545, RTS-1553

Depends on https://github.com/basho/riak_kv/pull/1624.

Tests for inverse distribution functions (PERCENTILE, MEDIAN).

2017-02-20 12:41 UTC, gordonguthrie commented
Is this PR agains the right base? surely `riak_ts-develop`?

2017-02-20 13:29 UTC, hmmr commented
Changed base.

2017-02-20 17:41 UTC, hazen requested changes
Just need to switch back changes to a bash script

2017-02-20 17:41 UTC, javajolt commented on bin/rtdev-setup-releases.sh
> +git config --local user.name "Riak Test"
Can you please revert these changes to this script? It is supposed to work on different versions of git now

2017-02-21 16:45 UTC, hazen approved these changes

2017-02-24 19:39 UTC, macintux commented
Would suggest including a test of a table where the column to be measured is defined as descending in the DDL.

2017-02-27 16:10 UTC, hmmr commented
@macintux now testing on tables with keys declared DESC, in aa4b672.

2017-02-28 17:31 UTC, macintux commented
+1

2017-02-28 21:15 UTC, merged